### ISSUE TITLE
1.13.0 计划

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/blog-timeline#2]
- [x] **内置友链朋友圈极简版** [hexo-circle-of-friends](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends)
- [ ] 默认数组配置改成字符串配置，例如 `widgets`
- [x] `timeline` 隐藏筛选的标签、支持隐藏标题、隐藏footer、取消最大高度限制
- [x] `friends/sites` 标签调整
- [x] `{% sites group1 %}`
- [ ] `ghrepo` 标签
- [x] `issues-api` 更新：
  - [x] `issue-json-generator` 用于解析并生成 `json`
  - [x] `raw.github.xaoxuu.com` 用于加速 `json` 文件访问

**Comment by abnerwei** [comment]
timeline 在文字超出范围时，呈现出来的滚动条略微影响观感

**Comment by xaoxuu** [comment]
你建议隐藏滚动条还是不限制最大高度呢？
